// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod spin {
  pub mod variables {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod variables {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      /// The set of errors which may be raised by functions in this interface.
      #[derive(Clone)]
      pub enum Error {
        /// The provided variable name is invalid.
        InvalidName(_rt::String),
        /// The provided variable is undefined.
        Undefined(_rt::String),
        /// A variables provider specific error has occurred.
        Provider(_rt::String),
        /// Some implementation-specific error has occurred.
        Other(_rt::String),
      }
      impl ::core::fmt::Debug for Error {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            Error::InvalidName(e) => {
              f.debug_tuple("Error::InvalidName").field(e).finish()
            }
            Error::Undefined(e) => {
              f.debug_tuple("Error::Undefined").field(e).finish()
            }
            Error::Provider(e) => {
              f.debug_tuple("Error::Provider").field(e).finish()
            }
            Error::Other(e) => {
              f.debug_tuple("Error::Other").field(e).finish()
            }
          }
        }
      }
      impl ::core::fmt::Display for Error {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{:?}", self)
        }
      }

      impl ::core::error::Error for Error {}
      #[allow(unused_unsafe, clippy::all)]
      /// Get an application variable value for the current component.
      ///
      /// The name must match one defined in in the component manifest.
      #[allow(async_fn_in_trait)]
      pub async fn get(name: _rt::String,) -> Result<_rt::String,Error>{
        unsafe {

          #[derive(Copy, Clone)]
          struct ParamsLower(
          *mut u8, usize, 
          );
          unsafe impl Send for ParamsLower {}
          

          use wit_bindgen::rt::async_support::Subtask as _Subtask;
          struct _MySubtask<'a> { _unused: core::marker::PhantomData<&'a ()> }
          #[allow(unused_parens)]
          unsafe impl<'a> _Subtask for _MySubtask<'a> {
            
            type Params = (_rt::String, );
            type Results = Result<_rt::String,Error>;
            type ParamsLower = ParamsLower;
            fn abi_layout(&mut self) -> ::core::alloc::Layout {
              unsafe {
                ::core::alloc::Layout::from_size_align_unchecked((4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>())
              }
            }
            
            fn results_offset(&mut self) -> usize { 0 }

            unsafe fn call_import(&mut self, _params: Self::ParamsLower, _results: *mut u8) -> u32 {
              
              #[cfg(target_arch = "wasm32")]
              #[link(wasm_import_module = "spin:variables/variables@3.0.0")]
              unsafe extern "C" {
                #[link_name = "[async-lower]get"]
                fn call(_: *mut u8, _: usize, _: *mut u8, ) -> i32;
              }

              #[cfg(not(target_arch = "wasm32"))]
              unsafe extern "C" fn call(_: *mut u8, _: usize, _: *mut u8, ) -> i32 { unreachable!() }
              
              unsafe { call(_params.0,_params.1,_results) as u32 }
            }
            
            unsafe fn params_dealloc_lists(&mut self, _params: Self::ParamsLower) {
              unsafe { _rt::cabi_dealloc(_params.0, _params.1, 1);
            }
          }
          unsafe fn params_dealloc_lists_and_own(&mut self, _params: Self::ParamsLower) {
            unsafe { _rt::cabi_dealloc(_params.0, _params.1, 1);
          }
        }
        unsafe fn params_lower(&mut self, (_lower0,): Self::Params, _ptr: *mut u8) -> Self::ParamsLower {
          unsafe { let vec0 = (_lower0.into_bytes()).into_boxed_slice();
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          ::core::mem::forget(vec0);
          ParamsLower(ptr0.cast_mut(), len0,) }
        }
        unsafe fn results_lift(&mut self, _ptr: *mut u8) -> Self::Results {
          unsafe { let l0 = i32::from(*_ptr.add(0).cast::<u8>());

          match l0 {
            0 => {
              let e = {
                let l1 = *_ptr.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l2 = *_ptr.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len3 = l2;
                let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);

                _rt::string_lift(bytes3)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l4 = i32::from(*_ptr.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                let v17 = match l4 {
                  0 => {
                    let e17 = {
                      let l5 = *_ptr.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l6 = *_ptr.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len7 = l6;
                      let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);

                      _rt::string_lift(bytes7)
                    };
                    Error::InvalidName(e17)
                  }
                  1 => {
                    let e17 = {
                      let l8 = *_ptr.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l9 = *_ptr.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len10 = l9;
                      let bytes10 = _rt::Vec::from_raw_parts(l8.cast(), len10, len10);

                      _rt::string_lift(bytes10)
                    };
                    Error::Undefined(e17)
                  }
                  2 => {
                    let e17 = {
                      let l11 = *_ptr.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l12 = *_ptr.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len13 = l12;
                      let bytes13 = _rt::Vec::from_raw_parts(l11.cast(), len13, len13);

                      _rt::string_lift(bytes13)
                    };
                    Error::Provider(e17)
                  }
                  n => {
                    debug_assert_eq!(n, 3, "invalid enum discriminant");
                    let e17 = {
                      let l14 = *_ptr.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l15 = *_ptr.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len16 = l15;
                      let bytes16 = _rt::Vec::from_raw_parts(l14.cast(), len16, len16);

                      _rt::string_lift(bytes16)
                    };
                    Error::Other(e17)
                  }
                };

                v17
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          } }
        }
      }
      _MySubtask { _unused: core::marker::PhantomData }.call((name,)).await
    }
  }

}

}
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]
  pub use alloc_crate::string::String;
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub use alloc_crate::vec::Vec;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  extern crate alloc as alloc_crate;
  pub use alloc_crate::alloc;
}

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.54.0:::component:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 259] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8c\x01\x01A\x02\x01\
A\x02\x01B\x05\x01q\x04\x0cinvalid-name\x01s\0\x09undefined\x01s\0\x08provider\x01\
s\0\x05other\x01s\0\x04\0\x05error\x03\0\0\x01j\x01s\x01\x01\x01C\x01\x04names\0\
\x02\x04\0\x03get\x01\x03\x03\0\x1espin:variables/variables@3.0.0\x05\0\x04\0\x02\
:/\x04\0\x0b\x06\x01\0\0\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-\
component\x070.245.1\x10wit-bindgen-rust\x060.54.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

