name: Release
on:
  push:
    tags:
      - "v*"

env:
  RUST_VERSION: 1.86

jobs:
  crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    if: github.repository_owner == 'spinframework'
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        shell: bash
        run: |
          rustup toolchain install ${{ env.RUST_VERSION }}
          rustup default ${{ env.RUST_VERSION }}

      - name: Publish spin-executor to crates.io
        working-directory: ./crates/executor
        run: |
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish spin-macro to crates.io
        working-directory: ./crates/macro
        run: |
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish spin-sdk to crates.io
        working-directory: ./
        run: |
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
